package io.gratia.app.service

import android.app.Service
import android.content.BroadcastReceiver
import android.content.Context
import android.content.Intent
import android.content.IntentFilter
import android.os.Build
import android.os.IBinder
import android.os.PowerManager
import android.util.Log
import androidx.work.ExistingPeriodicWorkPolicy
import androidx.work.PeriodicWorkRequestBuilder
import androidx.work.WorkManager
import androidx.work.Worker
import androidx.work.WorkerParameters
import io.gratia.app.sensors.SensorEventListener
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.cancel
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import java.util.Calendar
import java.util.TimeZone
import java.util.concurrent.TimeUnit

// WHY: These are imported as the UniFFI-generated bindings from the Rust core.
// The actual class names are generated by UniFFI at build time from gratia-ffi.
// In the generated code, GratiaNode is the main entry point and FfiSensorEvent
// is the enum for sensor events.
import uniffi.gratia.GratiaNode
import uniffi.gratia.FfiSensorEvent

/**
 * Foreground service for passive Proof of Life data collection.
 *
 * This service runs continuously in the background, collecting sensor
 * attestation data from normal phone usage. It has zero noticeable
 * battery impact because:
 * - Sensor managers use low-power / passive modes where available
 * - GPS uses the fused location provider at ~30-minute intervals
 * - Accelerometer and orientation use batched delivery
 * - Wi-Fi and Bluetooth scans piggyback on system scans
 *
 * The service:
 * 1. Starts all sensor managers on creation
 * 2. Receives sensor events via [SensorEventListener]
 * 3. Forwards events to the Rust core via [GratiaNode.submitSensorEvent]
 * 4. Handles day rollover at midnight UTC (calls finalize_day())
 * 5. Monitors battery/charging state for MiningService activation
 *
 * Lifecycle:
 * - Started on boot via [BootReceiver]
 * - Started when the app opens
 * - Runs as a foreground service with a silent persistent notification
 * - Survives app being swiped away (START_STICKY)
 * - Uses WorkManager for guaranteed periodic tasks (day finalization)
 */
class ProofOfLifeService : Service(), SensorEventListener {

    companion object {
        private const val TAG = "GratiaPoLService"

        /** WorkManager unique work name for the midnight day-finalization task. */
        const val WORK_FINALIZE_DAY = "gratia_finalize_day"

        /** WorkManager unique work name for the periodic keep-alive check. */
        const val WORK_KEEPALIVE = "gratia_pol_keepalive"

        /**
         * Singleton reference to the GratiaNode instance.
         *
         * WHY: The GratiaNode is thread-safe (all internal state is behind a Mutex)
         * and must be shared between ProofOfLifeService, MiningService, and the UI.
         * A singleton avoids creating multiple Rust-side instances which would have
         * separate PoL state, sensor buffers, and wallet references.
         */
        @Volatile
        var gratiaNode: GratiaNode? = null
            private set

        /**
         * Initialize the shared GratiaNode. Called once at app startup.
         * Safe to call multiple times; subsequent calls are no-ops.
         */
        fun initGratiaNode(dataDir: String) {
            if (gratiaNode == null) {
                synchronized(this) {
                    if (gratiaNode == null) {
                        gratiaNode = GratiaNode(dataDir)
                        Log.i(TAG, "GratiaNode initialized with dataDir=$dataDir")
                    }
                }
            }
        }
    }

    /** Coroutine scope tied to this service's lifecycle. */
    private val serviceScope = CoroutineScope(SupervisorJob() + Dispatchers.Default)

    /** Partial wake lock to keep the CPU alive during sensor processing in doze mode. */
    private var wakeLock: PowerManager.WakeLock? = null

    /**
     * Sensor managers — one per hardware sensor.
     *
     * WHY: We hold references so we can start/stop them cleanly. The actual
     * manager classes live in the sensors/ package and are initialized lazily
     * because some sensors may not be available on all devices.
     *
     * These are stored as Any because the sensor manager classes are defined
     * elsewhere and may not all be implemented yet. Each manager is expected
     * to accept a Context and a SensorEventListener in its constructor.
     */
    private val sensorManagers = mutableListOf<Any>()

    /** Receiver for screen-on/off and user-present events (unlock detection). */
    private var screenReceiver: BroadcastReceiver? = null

    /** Receiver for power/charging state changes. */
    private var powerReceiver: BroadcastReceiver? = null

    // -- Service Lifecycle -------------------------------------------------

    override fun onCreate() {
        super.onCreate()
        Log.i(TAG, "ProofOfLifeService created")

        // Create notification channels before posting any notification.
        NotificationHelper.createChannels(this)

        // WHY: Call startForeground() immediately in onCreate() to avoid ANR.
        // On Android 12+ the system gives only ~10 seconds after
        // startForegroundService() is called before killing the service.
        startForeground(
            NotificationHelper.NOTIFICATION_ID_POL,
            NotificationHelper.buildProofOfLifeNotification(this)
        )

        // Ensure GratiaNode is initialized. Use the app's internal files directory
        // which is private, encrypted at rest on most devices, and persists across
        // app updates.
        initGratiaNode(filesDir.absolutePath)

        // Acquire a partial wake lock to ensure sensor callbacks are processed
        // even when the screen is off. This is a PARTIAL lock — it does NOT
        // keep the screen on or prevent doze fully, but it keeps the CPU running
        // for brief processing windows.
        val powerManager = getSystemService(Context.POWER_SERVICE) as PowerManager
        wakeLock = powerManager.newWakeLock(
            PowerManager.PARTIAL_WAKE_LOCK,
            "gratia:proof_of_life"
        ).apply {
            // WHY: 10-minute timeout as a safety net. The lock is re-acquired
            // on each sensor event. This prevents a leaked wake lock from
            // draining the battery if the service crashes without cleanup.
            acquire(10 * 60 * 1000L)
        }

        // Start sensor collection.
        initializeSensors()
        registerScreenReceiver()
        registerPowerReceiver()

        // Schedule the midnight day-finalization via WorkManager.
        scheduleDayFinalization()

        // Schedule a periodic keep-alive to restart the service if killed.
        scheduleKeepAlive()

        // Start the midnight rollover coroutine for precise timing.
        startMidnightRolloverLoop()
    }

    override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {
        Log.d(TAG, "onStartCommand received")

        // WHY: START_STICKY tells the system to recreate the service if it's
        // killed due to memory pressure. PoL data collection must be continuous;
        // a gap of several hours could invalidate the day.
        return START_STICKY
    }

    override fun onBind(intent: Intent?): IBinder? {
        // WHY: This service is not bound — it runs independently. The UI
        // communicates with GratiaNode directly via the singleton reference.
        return null
    }

    override fun onDestroy() {
        Log.i(TAG, "ProofOfLifeService destroyed — cleaning up")

        // Cancel all coroutines.
        serviceScope.cancel()

        // Release wake lock.
        wakeLock?.let {
            if (it.isHeld) it.release()
        }
        wakeLock = null

        // Unregister broadcast receivers.
        screenReceiver?.let {
            try { unregisterReceiver(it) } catch (_: Exception) {}
        }
        screenReceiver = null

        powerReceiver?.let {
            try { unregisterReceiver(it) } catch (_: Exception) {}
        }
        powerReceiver = null

        // Stop sensor managers.
        stopSensors()

        super.onDestroy()
    }

    // -- Sensor Initialization ---------------------------------------------

    /**
     * Initialize and start all available sensor managers.
     *
     * Each manager is started in a try-catch so that a missing sensor
     * (e.g., barometer on a budget phone) does not prevent the service
     * from collecting data from sensors that ARE available.
     */
    private fun initializeSensors() {
        Log.i(TAG, "Initializing sensor managers")

        // WHY: Sensor managers are instantiated via reflection-style try/catch
        // rather than a hard dependency list. This ensures the service starts
        // even if some sensor manager classes are not yet implemented during
        // Phase 1 development.

        tryInitSensor("GPS") {
            io.gratia.app.sensors.GpsManager(this, this)
        }
        tryInitSensor("Accelerometer") {
            io.gratia.app.sensors.AccelerometerManager(this, this)
        }
        tryInitSensor("Bluetooth") {
            io.gratia.app.sensors.BluetoothManager(this, this)
        }
        tryInitSensor("WiFi") {
            io.gratia.app.sensors.WifiManager(this, this)
        }
        tryInitSensor("Battery") {
            io.gratia.app.sensors.BatteryManager(this, this)
        }
        tryInitSensor("Barometer") {
            io.gratia.app.sensors.BarometerManager(this, this)
        }
        tryInitSensor("Magnetometer") {
            io.gratia.app.sensors.MagnetometerManager(this, this)
        }
        tryInitSensor("LightSensor") {
            io.gratia.app.sensors.LightSensorManager(this, this)
        }
        tryInitSensor("NFC") {
            io.gratia.app.sensors.NfcManager(this, this)
        }

        Log.i(TAG, "Sensor initialization complete: ${sensorManagers.size} managers active")
    }

    /**
     * Attempt to initialize a single sensor manager. If the class is not
     * found or the sensor hardware is unavailable, log a warning and continue.
     */
    private fun tryInitSensor(name: String, factory: () -> Any) {
        try {
            val manager = factory()
            sensorManagers.add(manager)
            Log.d(TAG, "Sensor manager started: $name")
        } catch (e: Exception) {
            // WHY: Not all phones have all sensors. A budget phone from 2018
            // may lack a barometer or magnetometer. The core four (GPS,
            // accelerometer, Wi-Fi/BT, battery) are required; the rest only
            // boost the Presence Score.
            Log.w(TAG, "Sensor manager unavailable: $name — ${e.message}")
        }
    }

    /** Stop all sensor managers. */
    private fun stopSensors() {
        for (manager in sensorManagers) {
            try {
                // WHY: Sensor managers should implement a stop/destroy method.
                // We call it via duck-typing since the interface is not yet
                // standardized across all manager implementations.
                val stopMethod = manager.javaClass.getMethod("stop")
                stopMethod.invoke(manager)
            } catch (_: NoSuchMethodException) {
                // Manager does not have a stop() method — acceptable during
                // Phase 1 when interfaces are still being finalized.
            } catch (e: Exception) {
                Log.w(TAG, "Error stopping sensor manager: ${e.message}")
            }
        }
        sensorManagers.clear()
    }

    // -- Broadcast Receivers -----------------------------------------------

    /**
     * Register a receiver for screen-on / user-present events.
     *
     * WHY: Unlock detection is the primary PoL signal. The protocol requires
     * at least 10 unlocks spread across 6 hours. ACTION_USER_PRESENT fires
     * when the user dismisses the lockscreen, which is the closest Android
     * equivalent to an "unlock event."
     */
    private fun registerScreenReceiver() {
        screenReceiver = object : BroadcastReceiver() {
            override fun onReceive(context: Context, intent: Intent) {
                when (intent.action) {
                    Intent.ACTION_USER_PRESENT -> {
                        Log.d(TAG, "User present (unlock detected)")
                        onUnlock()
                    }
                    Intent.ACTION_SCREEN_ON -> {
                        // WHY: Screen-on without unlock (e.g., notification peek)
                        // is not counted as an unlock, but we log it for debugging.
                        Log.v(TAG, "Screen on")
                    }
                }
            }
        }

        val filter = IntentFilter().apply {
            addAction(Intent.ACTION_USER_PRESENT)
            addAction(Intent.ACTION_SCREEN_ON)
        }

        registerReceiver(screenReceiver, filter)
    }

    /**
     * Register a receiver for power/charging state changes.
     *
     * WHY: The PoL system needs to record charge cycle events (plug/unplug),
     * and the MiningService needs to be started/stopped based on power state.
     */
    private fun registerPowerReceiver() {
        powerReceiver = object : BroadcastReceiver() {
            override fun onReceive(context: Context, intent: Intent) {
                when (intent.action) {
                    Intent.ACTION_POWER_CONNECTED -> {
                        Log.i(TAG, "Power connected")
                        onChargeEvent(isCharging = true)
                        evaluateMiningConditions()
                    }
                    Intent.ACTION_POWER_DISCONNECTED -> {
                        Log.i(TAG, "Power disconnected")
                        onChargeEvent(isCharging = false)
                        // Stop mining immediately when unplugged.
                        stopMiningService()
                    }
                    Intent.ACTION_BATTERY_CHANGED -> {
                        evaluateMiningConditions()
                    }
                }
            }
        }

        val filter = IntentFilter().apply {
            addAction(Intent.ACTION_POWER_CONNECTED)
            addAction(Intent.ACTION_POWER_DISCONNECTED)
            addAction(Intent.ACTION_BATTERY_CHANGED)
        }

        registerReceiver(powerReceiver, filter)
    }

    // -- SensorEventListener Implementation --------------------------------

    override fun onUnlock() {
        submitEvent(FfiSensorEvent.Unlock)
    }

    override fun onInteraction(durationSecs: Int) {
        submitEvent(FfiSensorEvent.Interaction(durationSecs.toUInt()))
    }

    override fun onOrientationChange() {
        submitEvent(FfiSensorEvent.OrientationChange)
    }

    override fun onMotion() {
        submitEvent(FfiSensorEvent.Motion)
    }

    override fun onGpsUpdate(lat: Float, lon: Float) {
        submitEvent(FfiSensorEvent.GpsUpdate(lat, lon))
    }

    override fun onWifiScan(bssidHashes: List<Long>) {
        submitEvent(FfiSensorEvent.WifiScan(bssidHashes.map { it.toULong() }))
    }

    override fun onBluetoothScan(peerHashes: List<Long>) {
        submitEvent(FfiSensorEvent.BluetoothScan(peerHashes.map { it.toULong() }))
    }

    override fun onChargeEvent(isCharging: Boolean) {
        submitEvent(FfiSensorEvent.ChargeEvent(isCharging))
    }

    /**
     * Forward a sensor event to the Rust core. Runs on the Default dispatcher
     * to avoid blocking the calling thread (often the main thread for
     * broadcast receivers).
     */
    private fun submitEvent(event: FfiSensorEvent) {
        val node = gratiaNode ?: run {
            Log.w(TAG, "GratiaNode not initialized — dropping sensor event")
            return
        }

        serviceScope.launch {
            try {
                node.submitSensorEvent(event)
            } catch (e: Exception) {
                Log.e(TAG, "Failed to submit sensor event: ${e.message}")
            }
        }
    }

    // -- Mining Condition Evaluation ----------------------------------------

    /**
     * Check whether mining conditions are met and start/stop MiningService.
     *
     * Called whenever power state changes. The actual mining-eligibility logic
     * lives in the Rust core ([GratiaNode.updatePowerState]); we just read
     * the result and manage the Android service accordingly.
     */
    private fun evaluateMiningConditions() {
        val node = gratiaNode ?: return

        serviceScope.launch {
            try {
                val batteryManager = getSystemService(Context.BATTERY_SERVICE)
                    as android.os.BatteryManager
                val batteryPercent = batteryManager.getIntProperty(
                    android.os.BatteryManager.BATTERY_PROPERTY_CAPACITY
                ).coerceIn(0, 100)
                val isPluggedIn = batteryManager.isCharging

                val status = node.updatePowerState(isPluggedIn, batteryPercent.toUByte())

                when (status.state) {
                    "mining" -> startMiningService()
                    "battery_low", "proof_of_life" -> stopMiningService()
                    "throttled" -> {
                        // WHY: Keep MiningService running but in throttled state.
                        // The MiningService handles throttle internally.
                        Log.d(TAG, "Mining throttled due to thermal conditions")
                    }
                    "pending_activation" -> {
                        Log.d(TAG, "Mining pending — waiting for PoL or stake")
                    }
                }
            } catch (e: Exception) {
                Log.e(TAG, "Error evaluating mining conditions: ${e.message}")
            }
        }
    }

    private fun startMiningService() {
        Log.i(TAG, "Starting MiningService")
        val intent = Intent(this, MiningService::class.java)
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            startForegroundService(intent)
        } else {
            startService(intent)
        }
    }

    private fun stopMiningService() {
        Log.i(TAG, "Stopping MiningService")
        val intent = Intent(this, MiningService::class.java)
        stopService(intent)
    }

    // -- Day Rollover / Finalization ----------------------------------------

    /**
     * Coroutine that sleeps until midnight UTC and then calls finalize_day().
     *
     * WHY: WorkManager provides guaranteed execution but with imprecise timing
     * (can be delayed by up to 15 minutes in doze). This coroutine provides
     * precise midnight execution when the service is running. WorkManager
     * serves as a backup for when the service has been killed.
     */
    private fun startMidnightRolloverLoop() {
        serviceScope.launch {
            while (true) {
                val now = System.currentTimeMillis()
                val calendar = Calendar.getInstance(TimeZone.getTimeZone("UTC")).apply {
                    timeInMillis = now
                    add(Calendar.DAY_OF_YEAR, 1)
                    set(Calendar.HOUR_OF_DAY, 0)
                    set(Calendar.MINUTE, 0)
                    set(Calendar.SECOND, 0)
                    set(Calendar.MILLISECOND, 0)
                }
                val millisUntilMidnight = calendar.timeInMillis - now

                Log.d(TAG, "Next day finalization in ${millisUntilMidnight / 1000}s")
                delay(millisUntilMidnight)

                performDayFinalization()
            }
        }
    }

    /**
     * Finalize the current day's Proof of Life via the Rust core.
     *
     * Resets the sensor buffer for the new day. Logs whether the day was
     * valid or invalid.
     */
    private fun performDayFinalization() {
        val node = gratiaNode ?: run {
            Log.e(TAG, "Cannot finalize day — GratiaNode not initialized")
            return
        }

        try {
            val isValid = node.finalizeDay()
            if (isValid) {
                Log.i(TAG, "Day finalized: VALID")
            } else {
                Log.w(TAG, "Day finalized: INVALID — some PoL parameters were not met")
            }
        } catch (e: Exception) {
            Log.e(TAG, "Error finalizing day: ${e.message}")
        }
    }

    // -- WorkManager Scheduling --------------------------------------------

    /**
     * Schedule a periodic WorkManager task for day finalization.
     *
     * WHY: If the service is killed by the OS (aggressive battery optimization,
     * OEM-specific killing), WorkManager guarantees the day finalization still
     * runs. The 24-hour period with a 15-minute flex window is acceptable as
     * a fallback since the coroutine-based approach handles the precise case.
     */
    private fun scheduleDayFinalization() {
        val workRequest = PeriodicWorkRequestBuilder<DayFinalizationWorker>(
            24, TimeUnit.HOURS,
            15, TimeUnit.MINUTES  // Flex window
        ).build()

        WorkManager.getInstance(this).enqueueUniquePeriodicWork(
            WORK_FINALIZE_DAY,
            ExistingPeriodicWorkPolicy.KEEP,
            workRequest
        )
    }

    /**
     * Schedule a periodic keep-alive check.
     *
     * WHY: Some OEMs (Xiaomi, Huawei, Samsung) aggressively kill background
     * services. This WorkManager task runs every 15 minutes and restarts the
     * ProofOfLifeService if it has been killed.
     */
    private fun scheduleKeepAlive() {
        val workRequest = PeriodicWorkRequestBuilder<KeepAliveWorker>(
            15, TimeUnit.MINUTES,
            5, TimeUnit.MINUTES  // Flex window
        ).build()

        WorkManager.getInstance(this).enqueueUniquePeriodicWork(
            WORK_KEEPALIVE,
            ExistingPeriodicWorkPolicy.KEEP,
            workRequest
        )
    }

    // -- WorkManager Workers -----------------------------------------------

    /**
     * Worker that finalizes the day's Proof of Life.
     *
     * This is the WorkManager fallback for the coroutine-based midnight
     * rollover. It ensures finalization happens even if the service was killed.
     */
    class DayFinalizationWorker(
        appContext: Context,
        params: WorkerParameters
    ) : Worker(appContext, params) {

        override fun doWork(): Result {
            val node = gratiaNode
            if (node == null) {
                Log.w(TAG, "DayFinalizationWorker: GratiaNode not available")
                return Result.retry()
            }

            return try {
                val isValid = node.finalizeDay()
                Log.i(TAG, "DayFinalizationWorker: day finalized, valid=$isValid")
                Result.success()
            } catch (e: Exception) {
                Log.e(TAG, "DayFinalizationWorker failed: ${e.message}")
                Result.retry()
            }
        }
    }

    /**
     * Worker that checks if ProofOfLifeService is running and restarts it.
     */
    class KeepAliveWorker(
        private val appContext: Context,
        params: WorkerParameters
    ) : Worker(appContext, params) {

        override fun doWork(): Result {
            // WHY: The simplest keep-alive is to just call startForegroundService
            // again. If the service is already running, onStartCommand() is called
            // again (which is a no-op for us). If it was killed, it restarts.
            val intent = Intent(appContext, ProofOfLifeService::class.java)
            try {
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                    appContext.startForegroundService(intent)
                } else {
                    appContext.startService(intent)
                }
            } catch (e: Exception) {
                // WHY: On Android 12+ with restrictions on background starts,
                // this may throw. Not critical since the service will restart
                // on the next user interaction.
                Log.w(TAG, "KeepAliveWorker: could not restart service — ${e.message}")
            }
            return Result.success()
        }
    }
}
