package io.gratia.app.security

import android.content.Context
import android.content.SharedPreferences
import android.os.Build
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.security.keystore.StrongBoxUnavailableException
import android.util.Base64
import android.util.Log
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * Hardware-backed keystore for protecting Ed25519 wallet keys.
 *
 * WHY: Android Keystore does not natively support Ed25519 key generation or
 * signing. The Ed25519 key is generated by the Rust core (via dalek), so we
 * use Android Keystore to protect it at rest: an AES-256-GCM key is generated
 * inside the hardware security module (StrongBox or TEE), and that key
 * encrypts/decrypts the Ed25519 private key. The encrypted bytes are stored
 * in SharedPreferences. The AES key itself never leaves the secure hardware.
 *
 * Security layers:
 * 1. AES key lives in StrongBox (or TEE fallback) — extractable only by hardware
 * 2. Ed25519 key is AES-256-GCM encrypted at rest — ciphertext is useless without
 *    the hardware-bound AES key
 * 3. On signing, the key is decrypted into memory, used, then zeroed immediately
 */
object HardwareKeystore {

    private const val TAG = "HardwareKeystore"

    // WHY: The Android Keystore alias uniquely identifies our AES wrapping key
    // within the system keystore. Prefixed to avoid collisions with other apps
    // or libraries that also use Android Keystore.
    private const val AES_KEY_ALIAS = "gratia_wallet_wrapping_key"

    // WHY: SharedPreferences file name is separate from the app's default prefs
    // to keep wallet data isolated and easy to reason about during migration or
    // deletion.
    private const val PREFS_NAME = "gratia_hardware_keystore"

    // WHY: Two separate keys in SharedPreferences — the ciphertext and the IV
    // must both be stored because AES-GCM requires the exact IV used during
    // encryption to decrypt. A new random IV is generated for each encryption.
    private const val PREF_KEY_ENCRYPTED = "encrypted_wallet_key"
    private const val PREF_KEY_IV = "encrypted_wallet_iv"

    // WHY: GCM authentication tag length. 128 bits is the standard and maximum
    // for AES-GCM, providing strong authentication against tampering.
    private const val GCM_TAG_LENGTH_BITS = 128

    private lateinit var prefs: SharedPreferences
    private var isInitialized = false

    // WHY: Cached at init time so callers can query hardware backing status
    // without re-probing the keystore on every call.
    private var hardwareBacked = false

    /**
     * Initialize the hardware keystore.
     *
     * Must be called once at app startup (from GratiaApplication.onCreate).
     * Creates the AES-256-GCM wrapping key in Android Keystore if it does not
     * already exist. Tries StrongBox first, falls back to TEE.
     *
     * @param context Application context (for SharedPreferences access).
     */
    fun init(context: Context) {
        if (isInitialized) {
            Log.w(TAG, "HardwareKeystore already initialized, ignoring duplicate call")
            return
        }

        prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)

        // WHY: Check if the AES wrapping key already exists before generating.
        // On subsequent app launches, the key persists in Android Keystore.
        val keyStore = KeyStore.getInstance("AndroidKeyStore")
        keyStore.load(null)

        if (!keyStore.containsAlias(AES_KEY_ALIAS)) {
            hardwareBacked = generateAesKey()
            Log.i(TAG, "AES wrapping key created (hardware-backed: $hardwareBacked)")
        } else {
            // WHY: Key already exists. Determine if it's hardware-backed by
            // checking the key info. This is informational — the key works
            // regardless, but we report it for Presence Score and diagnostics.
            hardwareBacked = checkHardwareBacking(keyStore)
            Log.i(TAG, "AES wrapping key loaded (hardware-backed: $hardwareBacked)")
        }

        isInitialized = true
        Log.i(TAG, "HardwareKeystore initialized")
    }

    /**
     * Whether the AES wrapping key is backed by hardware (StrongBox or TEE).
     *
     * WHY: The Presence Score gives +8 points for secure enclave/TEE backing.
     * This method lets the PoL engine query hardware security status. Also
     * useful for the Settings screen to show the user their security level.
     *
     * @return true if StrongBox or TEE is protecting the key, false if software-only.
     */
    fun isHardwareBacked(): Boolean {
        checkInitialized()
        return hardwareBacked
    }

    /**
     * Encrypt the Ed25519 private key with the hardware-backed AES key.
     *
     * @param plainKey Raw 32-byte Ed25519 private key.
     * @return Encrypted bytes (ciphertext + GCM auth tag, variable length).
     * @throws SecurityException if encryption fails.
     */
    fun encryptKey(plainKey: ByteArray): ByteArray {
        checkInitialized()
        require(plainKey.size == 32) {
            // WHY: Ed25519 private keys are exactly 32 bytes. Reject anything
            // else to prevent accidentally encrypting garbage or truncated data.
            "Ed25519 private key must be exactly 32 bytes, got ${plainKey.size}"
        }

        try {
            val cipher = Cipher.getInstance("AES/GCM/NoPadding")
            cipher.init(Cipher.ENCRYPT_MODE, loadAesKey())

            // WHY: GCM generates a random IV internally when no IV is specified
            // in init(). We retrieve it after encryption to store alongside the
            // ciphertext. This is the standard pattern — never reuse an IV with
            // the same key, and letting the Cipher generate it guarantees uniqueness.
            val ciphertext = cipher.doFinal(plainKey)
            val iv = cipher.iv

            // WHY: Store IV separately because it's needed for decryption.
            // The IV is not secret — it's safe to store in plaintext. What
            // matters is that it's unique per encryption operation.
            return CiphertextWithIv(ciphertext, iv).encode()
        } catch (e: Exception) {
            Log.e(TAG, "Failed to encrypt wallet key", e)
            throw SecurityException("Failed to encrypt wallet key: ${e.message}", e)
        }
    }

    /**
     * Decrypt the Ed25519 private key using the hardware-backed AES key.
     *
     * @param encryptedKey Encoded bytes from [encryptKey] (ciphertext + IV).
     * @return Raw 32-byte Ed25519 private key.
     * @throws SecurityException if decryption fails (wrong key, tampered data, etc.).
     */
    fun decryptKey(encryptedKey: ByteArray): ByteArray {
        checkInitialized()

        try {
            val parsed = CiphertextWithIv.decode(encryptedKey)

            val cipher = Cipher.getInstance("AES/GCM/NoPadding")
            val spec = GCMParameterSpec(GCM_TAG_LENGTH_BITS, parsed.iv)
            cipher.init(Cipher.DECRYPT_MODE, loadAesKey(), spec)

            val plainKey = cipher.doFinal(parsed.ciphertext)

            if (plainKey.size != 32) {
                // WHY: Sanity check — if we get back something that isn't 32 bytes,
                // the encrypted data was corrupted or not an Ed25519 key.
                throw SecurityException(
                    "Decrypted key is ${plainKey.size} bytes, expected 32 — data may be corrupted"
                )
            }

            return plainKey
        } catch (e: SecurityException) {
            throw e
        } catch (e: Exception) {
            Log.e(TAG, "Failed to decrypt wallet key", e)
            throw SecurityException("Failed to decrypt wallet key: ${e.message}", e)
        }
    }

    /**
     * Encrypt the Ed25519 key and persist it to SharedPreferences.
     *
     * @param key Raw 32-byte Ed25519 private key.
     */
    fun storeWalletKey(key: ByteArray) {
        checkInitialized()

        val encrypted = encryptKey(key)
        val parsed = CiphertextWithIv.decode(encrypted)

        // WHY: Base64 encoding because SharedPreferences stores strings.
        // NO_WRAP avoids newlines in the encoded string.
        prefs.edit()
            .putString(PREF_KEY_ENCRYPTED, Base64.encodeToString(parsed.ciphertext, Base64.NO_WRAP))
            .putString(PREF_KEY_IV, Base64.encodeToString(parsed.iv, Base64.NO_WRAP))
            .apply()

        Log.i(TAG, "Wallet key stored (encrypted, hardware-backed: $hardwareBacked)")
    }

    /**
     * Load and decrypt the Ed25519 key from SharedPreferences.
     *
     * @return Raw 32-byte Ed25519 private key, or null if no key is stored.
     */
    fun loadWalletKey(): ByteArray? {
        checkInitialized()

        val encryptedB64 = prefs.getString(PREF_KEY_ENCRYPTED, null) ?: return null
        val ivB64 = prefs.getString(PREF_KEY_IV, null) ?: return null

        return try {
            val ciphertext = Base64.decode(encryptedB64, Base64.NO_WRAP)
            val iv = Base64.decode(ivB64, Base64.NO_WRAP)
            val encoded = CiphertextWithIv(ciphertext, iv).encode()
            decryptKey(encoded)
        } catch (e: Exception) {
            Log.e(TAG, "Failed to load wallet key from SharedPreferences", e)
            null
        }
    }

    /**
     * Whether an encrypted wallet key is stored in SharedPreferences.
     */
    fun hasStoredKey(): Boolean {
        checkInitialized()
        return prefs.contains(PREF_KEY_ENCRYPTED) && prefs.contains(PREF_KEY_IV)
    }

    /**
     * Delete both the encrypted wallet key from SharedPreferences and the AES
     * wrapping key from Android Keystore.
     *
     * WHY: Called during wallet reset or seed phrase re-import. Both must be
     * removed — leaving the AES key behind would be a dangling secret, and
     * leaving the encrypted key without the AES key would be unrecoverable
     * garbage.
     */
    fun deleteKey() {
        checkInitialized()

        // Remove encrypted key data from SharedPreferences
        prefs.edit()
            .remove(PREF_KEY_ENCRYPTED)
            .remove(PREF_KEY_IV)
            .apply()

        // Remove the AES wrapping key from Android Keystore
        try {
            val keyStore = KeyStore.getInstance("AndroidKeyStore")
            keyStore.load(null)
            if (keyStore.containsAlias(AES_KEY_ALIAS)) {
                keyStore.deleteEntry(AES_KEY_ALIAS)
                Log.i(TAG, "AES wrapping key deleted from Android Keystore")
            }
        } catch (e: Exception) {
            Log.e(TAG, "Failed to delete AES key from Keystore", e)
        }

        // WHY: Reset state so a subsequent init() creates a fresh AES key.
        hardwareBacked = false
        isInitialized = false

        Log.i(TAG, "Wallet key and wrapping key deleted")
    }

    // ========================================================================
    // Migration helper
    // ========================================================================

    /**
     * Migrate an unencrypted key file to the hardware keystore.
     *
     * WHY: Before hardware keystore integration, the Rust FileKeystore stored
     * the raw 32-byte Ed25519 key at {dataDir}/wallet_key.bin in plaintext.
     * This method reads that file, encrypts the key via Android Keystore, stores
     * it in SharedPreferences, and deletes the plaintext file. This is a one-time
     * migration that happens automatically at startup.
     *
     * @param dataDir The app's internal files directory path.
     * @return true if a key was migrated, false if no plaintext key file existed.
     */
    fun migrateFromPlaintextFile(dataDir: String): Boolean {
        checkInitialized()

        val keyFile = java.io.File("$dataDir/wallet_key.bin")
        if (!keyFile.exists()) {
            return false
        }

        // WHY: Don't migrate if we already have an encrypted key — this means
        // migration already happened and the file deletion failed or the file
        // was recreated by an older code path.
        if (hasStoredKey()) {
            Log.w(TAG, "Plaintext key file exists but hardware keystore already has a key. " +
                "Deleting plaintext file as safety measure.")
            secureDeleteFile(keyFile)
            return false
        }

        try {
            val rawKey = keyFile.readBytes()
            if (rawKey.size != 32) {
                Log.e(TAG, "Plaintext key file is ${rawKey.size} bytes, expected 32 — skipping migration")
                return false
            }

            // Encrypt and store in hardware keystore
            storeWalletKey(rawKey)

            // WHY: Zero the in-memory copy of the plaintext key before it goes
            // out of scope. This is defense-in-depth — the GC may not collect
            // the array immediately, but zeroing reduces the window.
            rawKey.fill(0)

            // WHY: Overwrite the file with zeros before deleting. A simple
            // delete() only removes the directory entry — the actual bytes may
            // persist on flash storage until overwritten. Writing zeros gives
            // us the best-effort guarantee that the plaintext key doesn't linger.
            secureDeleteFile(keyFile)

            Log.i(TAG, "Successfully migrated plaintext key to hardware keystore")
            return true
        } catch (e: Exception) {
            Log.e(TAG, "Failed to migrate plaintext key: ${e.message}", e)
            return false
        }
    }

    // ========================================================================
    // Private helpers
    // ========================================================================

    /**
     * Generate the AES-256-GCM wrapping key in Android Keystore.
     *
     * Tries StrongBox first (dedicated secure element, highest security), then
     * falls back to TEE (Trusted Execution Environment, still hardware-backed
     * but shared with the main processor's trust zone).
     *
     * @return true if the key is hardware-backed (StrongBox or TEE), false if
     *         software-only (should only happen on emulators or very old devices).
     */
    private fun generateAesKey(): Boolean {
        // WHY: Try StrongBox first. StrongBox is a dedicated secure element chip
        // (separate from the SoC) available on Pixel 3+ and Samsung Galaxy S10+.
        // It provides the strongest key isolation because the key material lives
        // on a physically separate chip with its own attack surface.
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
            try {
                val keyGen = KeyGenerator.getInstance(
                    KeyProperties.KEY_ALGORITHM_AES,
                    "AndroidKeyStore"
                )
                keyGen.init(
                    KeyGenParameterSpec.Builder(
                        AES_KEY_ALIAS,
                        KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT
                    )
                        .setKeySize(256)
                        .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                        .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                        // WHY: StrongBox provides the highest hardware security.
                        // If StrongBox is not available, this throws
                        // StrongBoxUnavailableException and we fall back to TEE.
                        .setIsStrongBoxBacked(true)
                        .build()
                )
                keyGen.generateKey()
                Log.i(TAG, "AES key generated in StrongBox")
                return true
            } catch (e: StrongBoxUnavailableException) {
                Log.i(TAG, "StrongBox not available, falling back to TEE")
                // Fall through to TEE attempt below
            } catch (e: Exception) {
                Log.w(TAG, "StrongBox key generation failed: ${e.message}, falling back to TEE")
                // Fall through to TEE attempt below
            }
        }

        // WHY: TEE fallback. The Trusted Execution Environment is available on
        // virtually all ARM devices manufactured after 2014. Keys are stored in
        // a secure world isolated from the Android OS. Not as strong as StrongBox
        // (shares the SoC) but vastly better than software-only key storage.
        try {
            val keyGen = KeyGenerator.getInstance(
                KeyProperties.KEY_ALGORITHM_AES,
                "AndroidKeyStore"
            )
            keyGen.init(
                KeyGenParameterSpec.Builder(
                    AES_KEY_ALIAS,
                    KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT
                )
                    .setKeySize(256)
                    .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                    .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                    // WHY: No StrongBox flag — lets the system use the best
                    // available hardware (TEE on most devices, software on emulators).
                    .build()
            )
            keyGen.generateKey()
            Log.i(TAG, "AES key generated in TEE")
            return true
        } catch (e: Exception) {
            Log.e(TAG, "TEE key generation failed: ${e.message} — using software keystore", e)
            return false
        }
    }

    /**
     * Load the AES wrapping key from Android Keystore.
     *
     * @return The AES SecretKey.
     * @throws SecurityException if the key cannot be loaded.
     */
    private fun loadAesKey(): SecretKey {
        try {
            val keyStore = KeyStore.getInstance("AndroidKeyStore")
            keyStore.load(null)
            val entry = keyStore.getEntry(AES_KEY_ALIAS, null) as? KeyStore.SecretKeyEntry
                ?: throw SecurityException("AES wrapping key not found in Android Keystore")
            return entry.secretKey
        } catch (e: SecurityException) {
            throw e
        } catch (e: Exception) {
            throw SecurityException("Failed to load AES key from Android Keystore: ${e.message}", e)
        }
    }

    /**
     * Check whether an existing key in Android Keystore is hardware-backed.
     *
     * WHY: After a key is created, we can query its KeyInfo to determine if it
     * resides in hardware. This is used on subsequent app launches (when the
     * key already exists) to set the hardwareBacked flag correctly.
     */
    private fun checkHardwareBacking(keyStore: KeyStore): Boolean {
        return try {
            val entry = keyStore.getEntry(AES_KEY_ALIAS, null) as? KeyStore.SecretKeyEntry
                ?: return false
            val key = entry.secretKey
            val factory = javax.crypto.SecretKeyFactory.getInstance(
                key.algorithm, "AndroidKeyStore"
            )
            val keyInfo = factory.getKeySpec(key, android.security.keystore.KeyInfo::class.java)
                as android.security.keystore.KeyInfo

            // WHY: getSecurityLevel() is API 31+ and gives granular StrongBox vs TEE
            // distinction. On older APIs, isInsideSecureHardware() returns true for
            // both StrongBox and TEE — still sufficient for our needs.
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
                keyInfo.securityLevel == android.security.keystore.KeyProperties.SECURITY_LEVEL_STRONGBOX ||
                    keyInfo.securityLevel == android.security.keystore.KeyProperties.SECURITY_LEVEL_TRUSTED_ENVIRONMENT
            } else {
                @Suppress("DEPRECATION")
                keyInfo.isInsideSecureHardware
            }
        } catch (e: Exception) {
            Log.w(TAG, "Could not determine hardware backing: ${e.message}")
            false
        }
    }

    /**
     * Overwrite a file with zeros before deleting.
     *
     * WHY: Flash storage wear-leveling means a simple File.delete() may leave
     * the original bytes on the physical medium. Writing zeros before deletion
     * is a best-effort mitigation — not a cryptographic guarantee (the flash
     * controller may remap sectors), but it eliminates the most common recovery
     * vectors (file system tools, undelete utilities).
     */
    private fun secureDeleteFile(file: java.io.File) {
        try {
            if (file.exists()) {
                val length = file.length()
                java.io.FileOutputStream(file).use { fos ->
                    fos.write(ByteArray(length.toInt()))
                    fos.flush()
                    fos.fd.sync()
                }
                file.delete()
            }
        } catch (e: Exception) {
            // WHY: Best effort — if we can't zero the file, at least try to delete it.
            Log.w(TAG, "Secure delete failed, attempting plain delete: ${e.message}")
            file.delete()
        }
    }

    private fun checkInitialized() {
        check(isInitialized) {
            "HardwareKeystore not initialized. Call init(context) first."
        }
    }

    // ========================================================================
    // Ciphertext encoding
    // ========================================================================

    /**
     * Bundles ciphertext and IV into a single byte array for transport.
     *
     * WHY: encryptKey/decryptKey operate on single byte arrays. This encoding
     * packs the IV length (1 byte), IV, and ciphertext into one blob so the
     * caller doesn't need to manage two separate byte arrays. The format is:
     *
     *   [iv_length: 1 byte] [iv: iv_length bytes] [ciphertext: remaining bytes]
     *
     * AES-GCM IVs are always 12 bytes, but encoding the length makes the format
     * forward-compatible if the IV size ever changes.
     */
    private data class CiphertextWithIv(val ciphertext: ByteArray, val iv: ByteArray) {
        fun encode(): ByteArray {
            val result = ByteArray(1 + iv.size + ciphertext.size)
            result[0] = iv.size.toByte()
            System.arraycopy(iv, 0, result, 1, iv.size)
            System.arraycopy(ciphertext, 0, result, 1 + iv.size, ciphertext.size)
            return result
        }

        companion object {
            fun decode(encoded: ByteArray): CiphertextWithIv {
                require(encoded.size > 1) { "Encoded ciphertext too short" }
                val ivLength = encoded[0].toInt() and 0xFF
                require(encoded.size > 1 + ivLength) { "Encoded ciphertext truncated" }
                val iv = encoded.copyOfRange(1, 1 + ivLength)
                val ciphertext = encoded.copyOfRange(1 + ivLength, encoded.size)
                return CiphertextWithIv(ciphertext, iv)
            }
        }

        // WHY: data class with ByteArray needs manual equals/hashCode because
        // the default data class implementations use reference equality for arrays.
        override fun equals(other: Any?): Boolean {
            if (this === other) return true
            if (other !is CiphertextWithIv) return false
            return ciphertext.contentEquals(other.ciphertext) && iv.contentEquals(other.iv)
        }

        override fun hashCode(): Int {
            return 31 * ciphertext.contentHashCode() + iv.contentHashCode()
        }
    }
}
