//! Proof of Life - Passive attestation engine for the Gratia protocol.
//!
//! This crate handles:
//! - Collecting and validating daily Proof of Life parameters
//! - Building ZK attestations from raw sensor data (on-device only)
//! - Managing onboarding and grace periods
//! - Behavioral pattern matching for wallet recovery
//!
//! PRIVACY: Raw sensor data is processed exclusively within this crate
//! on the local device. Only zero-knowledge attestations leave the phone.

pub mod collector;
pub mod validator;
pub mod behavioral;
pub mod behavioral_anomaly;
pub mod clustering;
pub mod trust;
pub mod tee;
pub mod scoring;

use gratia_core::{
    DailyProofOfLifeData, MiningState, PowerState, GeoLocation,
    config::Config,
};
use gratia_zk::bulletproofs::{PolProofInput, PolRangeProof, PolThresholds};
use chrono::{NaiveDate, Utc};
use std::collections::VecDeque;

/// Manages Proof of Life state for a single node.
pub struct ProofOfLifeManager {
    config: Config,
    current_day_data: DailyProofOfLifeData,
    valid_days: VecDeque<NaiveDate>,
    consecutive_valid_days: u64,
    consecutive_missed_days: u32,
    onboarding_complete: bool,
    mining_eligible: bool,
    /// The ZK proof generated by the most recent successful finalize_day().
    /// WHY: Stored here so that the attestation builder (or FFI layer) can
    /// retrieve it after finalize_day() returns true, without changing the
    /// finalize_day() return type and breaking existing callers.
    last_zk_proof: Option<PolRangeProof>,
    /// WHY: After an app restart, current_day_data is empty because sensor
    /// events aren't persisted. But if the phone had valid PoL before the
    /// restart (onboarding_complete=true), we grant a warm-start grace period
    /// so the user doesn't have to wait for sensor re-collection. The PoL
    /// service will re-populate sensor data in the background; this just
    /// bridges the gap so mining isn't interrupted by routine app restarts.
    warm_start_until: Option<std::time::Instant>,
}

impl ProofOfLifeManager {
    pub fn new(config: Config) -> Self {
        ProofOfLifeManager {
            config,
            current_day_data: DailyProofOfLifeData {
                unlock_count: 0,
                first_unlock: None,
                last_unlock: None,
                interaction_sessions: 0,
                orientation_changed: false,
                human_motion_detected: false,
                gps_fix_obtained: false,
                approximate_location: None,
                distinct_wifi_networks: 0,
                distinct_bt_environments: 0,
                bt_environment_change_count: 0,
                charge_cycle_event: false,
                optional_sensors: Default::default(),
            },
            valid_days: VecDeque::new(),
            consecutive_valid_days: 0,
            consecutive_missed_days: 0,
            onboarding_complete: false,
            mining_eligible: false,
            last_zk_proof: None,
            warm_start_until: None,
        }
    }

    /// Record a phone unlock event.
    pub fn record_unlock(&mut self) {
        let now = Utc::now();
        self.current_day_data.unlock_count += 1;
        if self.current_day_data.first_unlock.is_none() {
            self.current_day_data.first_unlock = Some(now);
        }
        self.current_day_data.last_unlock = Some(now);
    }

    /// Record a screen interaction session.
    pub fn record_interaction_session(&mut self) {
        self.current_day_data.interaction_sessions += 1;
    }

    /// Record an orientation change.
    pub fn record_orientation_change(&mut self) {
        self.current_day_data.orientation_changed = true;
    }

    /// Record human-consistent motion detection.
    pub fn record_human_motion(&mut self) {
        self.current_day_data.human_motion_detected = true;
    }

    /// Record a GPS fix.
    pub fn record_gps_fix(&mut self, lat: f32, lon: f32) {
        self.current_day_data.gps_fix_obtained = true;
        self.current_day_data.approximate_location = Some(GeoLocation { lat, lon });
    }

    /// Record a distinct Wi-Fi network seen.
    pub fn record_wifi_network(&mut self) {
        self.current_day_data.distinct_wifi_networks += 1;
    }

    /// Record a Bluetooth environment change.
    pub fn record_bt_environment_change(&mut self) {
        self.current_day_data.distinct_bt_environments += 1;
    }

    /// Record a charge cycle event (plug/unplug).
    pub fn record_charge_event(&mut self) {
        self.current_day_data.charge_cycle_event = true;
    }

    /// Finalize the day's Proof of Life. Returns whether the day was valid.
    ///
    /// When the day is valid, a ZK Bulletproof is generated proving that
    /// the core numeric PoL parameters met their thresholds. The proof is
    /// stored internally and can be retrieved via `last_zk_proof()`.
    pub fn finalize_day(&mut self, epoch_day: u32) -> bool {
        let today = Utc::now().date_naive();
        let is_valid = self.current_day_data.is_valid(&self.config.proof_of_life);

        // Clear previous proof regardless of outcome.
        self.last_zk_proof = None;

        if is_valid {
            // Generate ZK proof from the daily data before we reset it.
            // WHY: The proof must be generated while we still have access to the
            // raw sensor values. After reset, these values are gone. The proof
            // demonstrates the parameters were met without revealing actual values.
            let unlock_spread_hours = match (self.current_day_data.first_unlock, self.current_day_data.last_unlock) {
                (Some(first), Some(last)) => (last - first).num_hours().max(0) as u64,
                _ => 0,
            };

            let proof_input = PolProofInput {
                unlock_count: self.current_day_data.unlock_count as u64,
                unlock_spread_hours,
                interaction_sessions: self.current_day_data.interaction_sessions as u64,
                bt_environments: self.current_day_data.distinct_bt_environments as u64,
            };

            let thresholds = PolThresholds {
                min_unlocks: self.config.proof_of_life.min_daily_unlocks as u64,
                min_spread: self.config.proof_of_life.min_unlock_spread_hours as u64,
                min_interactions: self.config.proof_of_life.min_interaction_sessions as u64,
                min_bt_envs: self.config.proof_of_life.min_distinct_bt_environments as u64,
            };

            match gratia_zk::generate_pol_proof(&proof_input, &thresholds, epoch_day) {
                Ok(proof) => {
                    tracing::info!(
                        proof_bytes = proof.proof_bytes.len(),
                        commitments = proof.commitments.len(),
                        "ZK Bulletproof generated for daily PoL attestation"
                    );
                    self.last_zk_proof = Some(proof);
                }
                Err(e) => {
                    // WHY: Proof generation failure should not invalidate the day.
                    // The PoL data was valid — the ZK proof is an additional layer.
                    // Log the error so it can be investigated, but don't penalize
                    // the user for a cryptographic library issue.
                    tracing::error!(error = %e, "ZK proof generation failed for valid PoL day");
                }
            }

            self.valid_days.push_back(today);
            self.consecutive_valid_days += 1;
            self.consecutive_missed_days = 0;

            if !self.onboarding_complete {
                self.onboarding_complete = true;
            }

            self.mining_eligible = true;

            while self.valid_days.len() > 365 {
                self.valid_days.pop_front();
            }
        } else {
            self.consecutive_missed_days += 1;

            if self.consecutive_missed_days >= self.config.proof_of_life.grace_period_days + 1 {
                self.mining_eligible = false;
                self.consecutive_valid_days = 0;
            }
        }

        // Reset for next day
        self.current_day_data = DailyProofOfLifeData {
            unlock_count: 0,
            first_unlock: None,
            last_unlock: None,
            interaction_sessions: 0,
            orientation_changed: false,
            human_motion_detected: false,
            gps_fix_obtained: false,
            approximate_location: None,
            distinct_wifi_networks: 0,
            distinct_bt_environments: 0,
            bt_environment_change_count: 0,
            charge_cycle_event: false,
            optional_sensors: Default::default(),
        };

        is_valid
    }

    /// Check if this node is currently eligible for mining.
    pub fn is_mining_eligible(&self) -> bool {
        self.onboarding_complete && self.mining_eligible
    }

    /// Check if onboarding is complete.
    pub fn is_onboarded(&self) -> bool {
        self.onboarding_complete
    }

    /// Get total valid PoL days.
    pub fn participation_days(&self) -> u64 {
        self.valid_days.len() as u64
    }

    /// Get consecutive valid days.
    pub fn consecutive_days(&self) -> u64 {
        self.consecutive_valid_days
    }

    /// Get the ZK proof from the most recent successful finalize_day().
    ///
    /// Returns `None` if the last finalize_day() was invalid, or if no
    /// finalize_day() has been called yet, or if proof generation failed.
    pub fn last_zk_proof(&self) -> Option<&PolRangeProof> {
        self.last_zk_proof.as_ref()
    }

    /// Take the ZK proof from the most recent successful finalize_day(),
    /// consuming it from the manager. Useful when building attestations
    /// to avoid cloning the proof bytes.
    pub fn take_last_zk_proof(&mut self) -> Option<PolRangeProof> {
        self.last_zk_proof.take()
    }

    /// Save PoL state to a file for persistence across restarts.
    /// WHY: The consecutive day streak and onboarding status must survive
    /// app restarts. Without this, the trust tier resets to Unverified
    /// every time the app is killed and restarted.
    pub fn save_state(&self, data_dir: &str) {
        let path = format!("{}/pol_state.bin", data_dir);
        // Format: 8 bytes consecutive_days + 8 bytes total_days + 1 byte onboarded
        let mut data = Vec::with_capacity(17);
        data.extend_from_slice(&self.consecutive_valid_days.to_le_bytes());
        data.extend_from_slice(&(self.valid_days.len() as u64).to_le_bytes());
        data.push(if self.onboarding_complete { 1 } else { 0 });
        let _ = std::fs::write(&path, &data);
    }

    /// Load PoL state from a file.
    pub fn load_state(&mut self, data_dir: &str) {
        let path = format!("{}/pol_state.bin", data_dir);
        if let Ok(data) = std::fs::read(&path) {
            if data.len() != 17 {
                tracing::warn!(
                    actual_len = data.len(),
                    expected_len = 17,
                    "PoL state file has unexpected size — skipping load to avoid corrupt state"
                );
                return;
            }
            if data.len() >= 17 {
                self.consecutive_valid_days = u64::from_le_bytes(
                    data[0..8].try_into().unwrap_or([0; 8]),
                );
                let total_days = u64::from_le_bytes(
                    data[8..16].try_into().unwrap_or([0; 8]),
                );
                self.onboarding_complete = data[16] != 0;
                self.mining_eligible = self.onboarding_complete;

                // WHY: Reconstruct valid_days with placeholder dates.
                // The exact dates don't matter for the streak counter —
                // what matters is the count for trust tier calculation.
                let today = Utc::now().date_naive();
                self.valid_days.clear();
                for i in 0..total_days.min(365) {
                    if let Some(d) = today.checked_sub_signed(chrono::Duration::days(i as i64)) {
                        self.valid_days.push_back(d);
                    }
                }

                // WHY: Grant 10-minute warm-start grace after loading persisted
                // state. This lets the PoL service re-collect sensor events in
                // the background while mining resumes immediately. 10 minutes is
                // enough for unlocks, orientation changes, and GPS fixes to
                // re-populate current_day_data through normal phone usage.
                if self.onboarding_complete {
                    self.warm_start_until = Some(
                        std::time::Instant::now() + std::time::Duration::from_secs(600)
                    );
                }

                tracing::info!(
                    consecutive = self.consecutive_valid_days,
                    total = total_days,
                    onboarded = self.onboarding_complete,
                    warm_start = self.warm_start_until.is_some(),
                    "PoL state restored from persistence"
                );
            }
        }
    }

    /// Check current day's validity in real-time.
    pub fn current_day_valid(&self) -> bool {
        // WHY: Warm-start grace — after app restart, sensor data hasn't been
        // re-collected yet but the phone was previously verified. Accept the
        // cached PoL validity for a short window so mining resumes immediately.
        if let Some(until) = self.warm_start_until {
            if until.elapsed().as_secs() == 0 || std::time::Instant::now() < until {
                return true;
            }
        }
        self.current_day_data.is_valid(&self.config.proof_of_life)
    }

    /// Check if this node is still in its onboarding period (day 0).
    /// WHY: Day 0 users have never completed a PoL cycle yet. They are allowed
    /// to mine immediately per the zero-delay onboarding design. Once
    /// onboarding_complete is set (after first finalize_day with valid data),
    /// this returns false and real PoL is required going forward.
    pub fn is_onboarding(&self) -> bool {
        !self.onboarding_complete
    }

    /// Check if the node is within the 1-day grace period for missed PoL.
    /// WHY: A single missed day should not immediately kill mining. The protocol
    /// allows 1 grace day. Two consecutive missed days pauses mining.
    pub fn in_grace_period(&self) -> bool {
        self.onboarding_complete
            && self.consecutive_missed_days > 0
            && self.consecutive_missed_days <= self.config.proof_of_life.grace_period_days
    }

    /// Get the number of consecutive missed days.
    pub fn missed_days(&self) -> u32 {
        self.consecutive_missed_days
    }

    /// Count how many of the 8 daily PoL parameters are currently met.
    /// WHY: Health telemetry needs a quick summary of PoL progress without
    /// exposing raw sensor data. Returns 0-8.
    pub fn parameters_met_count(&self) -> u8 {
        let cfg = &self.config.proof_of_life;
        let d = &self.current_day_data;
        let mut count: u8 = 0;

        // 1. Unlocks (count + spread)
        let spread_ok = match (d.first_unlock, d.last_unlock) {
            (Some(first), Some(last)) => (last - first).num_hours() >= cfg.min_unlock_spread_hours as i64,
            _ => false,
        };
        if d.unlock_count >= cfg.min_daily_unlocks && spread_ok { count += 1; }

        // 2. Screen interactions
        if d.interaction_sessions >= cfg.min_interaction_sessions { count += 1; }

        // 3. Orientation change
        if d.orientation_changed { count += 1; }

        // 4. Human motion
        if d.human_motion_detected { count += 1; }

        // 5. GPS fix
        if d.gps_fix_obtained { count += 1; }

        // 6. Network connectivity (Wi-Fi OR Bluetooth)
        if d.distinct_wifi_networks >= 1 || d.distinct_bt_environments >= 1 { count += 1; }

        // 7. BT variation (passes if no BT, or if BT shows variation)
        let bt_variation_ok = d.distinct_bt_environments == 0
            || (d.distinct_bt_environments >= cfg.min_distinct_bt_environments
                && d.bt_environment_change_count >= 1);
        if bt_variation_ok { count += 1; }

        // 8. Charge cycle event
        if d.charge_cycle_event { count += 1; }

        count
    }

    /// Determine mining state based on current conditions.
    pub fn determine_mining_state(&self, power: &PowerState, has_minimum_stake: bool) -> MiningState {
        if !self.is_mining_eligible() {
            return MiningState::ProofOfLife;
        }
        if !power.is_plugged_in {
            return MiningState::ProofOfLife;
        }
        if power.is_throttled {
            return MiningState::Throttled;
        }
        if power.battery_percent < self.config.mining.min_battery_percent {
            return MiningState::BatteryLow;
        }
        if !has_minimum_stake {
            return MiningState::PendingActivation;
        }
        MiningState::Mining
    }
}
